from typing import Dict, List

from utils.parsers import calculate_statistics


class StatsAnalyzer:
    def analyze_sales(self, records: List[Dict[str, object]]) -> Dict[str, object]:
        amounts = [float(r["quantity"]) * float(r["price"]) for r in records]
        stats = calculate_statistics(amounts)
        by_region: Dict[str, float] = {}
        for rec in records:
            region = str(rec["region"])
            amount = float(rec["quantity"]) * float(rec["price"])
            by_region[region] = by_region.get(region, 0.0) + amount
        return {"stats": stats, "by_region": by_region}
# stats analyzer padding line 16
# stats analyzer padding line 17
# stats analyzer padding line 18
# stats analyzer padding line 19
# stats analyzer padding line 20
# stats analyzer padding line 21
# stats analyzer padding line 22
# stats analyzer padding line 23
# stats analyzer padding line 24
# stats analyzer padding line 25
# stats analyzer padding line 26
# stats analyzer padding line 27
# stats analyzer padding line 28
# stats analyzer padding line 29
# stats analyzer padding line 30
# stats analyzer padding line 31
# stats analyzer padding line 32
# stats analyzer padding line 33
# stats analyzer padding line 34
# stats analyzer padding line 35
# stats analyzer padding line 36
# stats analyzer padding line 37
# stats analyzer padding line 38
# stats analyzer padding line 39
# stats analyzer padding line 40
# stats analyzer padding line 41
# stats analyzer padding line 42
# stats analyzer padding line 43
# stats analyzer padding line 44
# stats analyzer padding line 45
# stats analyzer padding line 46
# stats analyzer padding line 47
# stats analyzer padding line 48
# stats analyzer padding line 49
# stats analyzer padding line 50
# stats analyzer padding line 51
# stats analyzer padding line 52
# stats analyzer padding line 53
# stats analyzer padding line 54
# stats analyzer padding line 55
# stats analyzer padding line 56
# stats analyzer padding line 57
# stats analyzer padding line 58
# stats analyzer padding line 59
# stats analyzer padding line 60
# stats analyzer padding line 61
# stats analyzer padding line 62
# stats analyzer padding line 63
# stats analyzer padding line 64
# stats analyzer padding line 65
# stats analyzer padding line 66
# stats analyzer padding line 67
# stats analyzer padding line 68
# stats analyzer padding line 69
# stats analyzer padding line 70
# stats analyzer padding line 71
# stats analyzer padding line 72
# stats analyzer padding line 73
# stats analyzer padding line 74
# stats analyzer padding line 75
# stats analyzer padding line 76
# stats analyzer padding line 77
# stats analyzer padding line 78
# stats analyzer padding line 79
# stats analyzer padding line 80
# stats analyzer padding line 81
# stats analyzer padding line 82
# stats analyzer padding line 83
# stats analyzer padding line 84
# stats analyzer padding line 85
# stats analyzer padding line 86
# stats analyzer padding line 87
# stats analyzer padding line 88
# stats analyzer padding line 89
# stats analyzer padding line 90
# stats analyzer padding line 91
# stats analyzer padding line 92
# stats analyzer padding line 93
# stats analyzer padding line 94
# stats analyzer padding line 95
# stats analyzer padding line 96
# stats analyzer padding line 97
# stats analyzer padding line 98
# stats analyzer padding line 99
# stats analyzer padding line 100
# stats analyzer padding line 101
# stats analyzer padding line 102
# stats analyzer padding line 103
# stats analyzer padding line 104
# stats analyzer padding line 105
# stats analyzer padding line 106
# stats analyzer padding line 107
# stats analyzer padding line 108
# stats analyzer padding line 109
# stats analyzer padding line 110
# stats analyzer padding line 111
# stats analyzer padding line 112
# stats analyzer padding line 113
# stats analyzer padding line 114
# stats analyzer padding line 115
# stats analyzer padding line 116
# stats analyzer padding line 117
# stats analyzer padding line 118
# stats analyzer padding line 119
# stats analyzer padding line 120
# stats analyzer padding line 121
# stats analyzer padding line 122
# stats analyzer padding line 123
# stats analyzer padding line 124
# stats analyzer padding line 125
# stats analyzer padding line 126
# stats analyzer padding line 127
# stats analyzer padding line 128
# stats analyzer padding line 129
# stats analyzer padding line 130
# stats analyzer padding line 131
# stats analyzer padding line 132
# stats analyzer padding line 133
# stats analyzer padding line 134
# stats analyzer padding line 135
# stats analyzer padding line 136
# stats analyzer padding line 137
# stats analyzer padding line 138
# stats analyzer padding line 139
# stats analyzer padding line 140
# stats analyzer padding line 141
# stats analyzer padding line 142
# stats analyzer padding line 143
# stats analyzer padding line 144
# stats analyzer padding line 145
# stats analyzer padding line 146
# stats analyzer padding line 147
# stats analyzer padding line 148
# stats analyzer padding line 149
# stats analyzer padding line 150
# stats analyzer padding line 151
# stats analyzer padding line 152
# stats analyzer padding line 153
# stats analyzer padding line 154
# stats analyzer padding line 155
# stats analyzer padding line 156
# stats analyzer padding line 157
# stats analyzer padding line 158
# stats analyzer padding line 159
# stats analyzer padding line 160
# stats analyzer padding line 161
# stats analyzer padding line 162
# stats analyzer padding line 163
# stats analyzer padding line 164
# stats analyzer padding line 165
# stats analyzer padding line 166
# stats analyzer padding line 167
# stats analyzer padding line 168
# stats analyzer padding line 169
# stats analyzer padding line 170
# stats analyzer padding line 171
# stats analyzer padding line 172
# stats analyzer padding line 173
# stats analyzer padding line 174
# stats analyzer padding line 175
# stats analyzer padding line 176
# stats analyzer padding line 177
# stats analyzer padding line 178
# stats analyzer padding line 179
# stats analyzer padding line 180
# stats analyzer padding line 181
# stats analyzer padding line 182
# stats analyzer padding line 183
# stats analyzer padding line 184
# stats analyzer padding line 185
# stats analyzer padding line 186
# stats analyzer padding line 187
# stats analyzer padding line 188
# stats analyzer padding line 189
# stats analyzer padding line 190
# stats analyzer padding line 191
# stats analyzer padding line 192
# stats analyzer padding line 193
# stats analyzer padding line 194
# stats analyzer padding line 195
# stats analyzer padding line 196
# stats analyzer padding line 197
# stats analyzer padding line 198
# stats analyzer padding line 199
# stats analyzer padding line 200
